version: '3'
services:
  mysql80:
    image: mysql:8.0
    container_name: canary-platform-mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ldap123456
    restart: always
  canary-platform:
    # image: yiluxiangbei/canary-platform:20220424
    build:
      context: canary-fe
      dockerfile: Dockerfile
    container_name: canary-platform-fe
    ports:
      - "8072:8080"
    volumes:
      - ./canary/data:/canary-platform/data
      - ./canary/logs:/canary-platform/logs
      - ../accounts:/canary-platform/accounts
      - ../canary_platform:/canary-platform/canary_platform
      - /etc/localtime:/etc/localtime
    #depends_on:
    #  - mysql80
    restart: always